name: Bug 反馈
description: 创建报告，帮助我们改进项目
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: 描述此Bug
      description: 简明扼要地描述错误是什么。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 复现方式
      description: 详细描述如何复现此Bug。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 期望行为
      description: 描述你期望的行为是什么。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 截图
      description: 如果可以，请提供相关截图。

  - type: input
    attributes:
      label: 平台
      description: 例如：Windows 10, Ubuntu 22.04.
    validations:
      required: true

  - type: input
    attributes:
      label: v8wrap 版本
      description: 例如：v1.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: 其他信息
      description: 例如：错误日志、相关代码等。
